image:
- Ubuntu
  stack:
    - node 7
    - node 8
    - node 9
- Visual Studio 2017
  matrix:
    - nodejs_version: 7
      platform:
        - x86
        - x64
    - nodejs_version: LTS
      platform:
        - x86
        - x64
    - nodejs_version: Current
      platform:
        - x86
        - x64
environment:
  APPVEYOR_YML_DISABLE_PS_LINUX: true
cache:
  - node_modules
install:
  - sh: uname -m
  - sh: uname -a
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_REPO_BRANCH-$env:APPVEYOR_BUILD_NUMBER"
test_script:
  - node --version
  - npm --version
  - npm test
build: off